# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_telegram1', '0002_intent_intent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='story_action',
            name='msg_example',
            field=models.TextField(default=' '),
        ),
    ]
