# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_telegram1', '0003_story_action_msg_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date_in_s',
        ),
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
