# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_id',
            fields=[
                ('idnumber', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=61)),
                ('value', models.CharField(max_length=60)),
                ('confidence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(default=' ', max_length=200)),
                ('date_in_s', models.BigIntegerField()),
                ('viewed', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='Story_entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Context_chat',
            fields=[
                ('chat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assistant_telegram.Chat_id')),
                ('validated_action', models.BooleanField()),
                ('prev_msg_from_bot', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Story_action',
            fields=[
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assistant_telegram.Intent')),
                ('validation_option', models.BooleanField(default='False')),
                ('action_name', models.CharField(default=' ', max_length=60)),
                ('action_answer', models.TextField(default=' ')),
                ('transcript', models.CharField(default=' ', max_length=60)),
                ('desc', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Story_msg',
            fields=[
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assistant_telegram.Intent')),
                ('msg_example', models.TextField(default=' ')),
                ('answer', models.TextField(default=' ')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='chat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant_telegram.Chat_id'),
        ),
        migrations.AddField(
            model_name='log',
            name='intent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant_telegram.Intent'),
        ),
        migrations.AddField(
            model_name='story_entity',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_telegram.Story_action'),
        ),
        migrations.AddField(
            model_name='entity',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant_telegram.Context_chat'),
        ),
        migrations.AddField(
            model_name='context_chat',
            name='intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assistant_telegram.Intent'),
        ),
    ]
