# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_telegram', '0002_auto_20171025_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='validation_option',
            field=models.BooleanField(default='False'),
        ),
    ]
