# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_telegram', '0006_auto_20171026_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_id',
            fields=[
                ('idnumber', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='date_in_s',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='viewed',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='context_chat',
            name='chat_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assistant_telegram.Chat_id'),
        ),
        migrations.AlterField(
            model_name='context_chat',
            name='intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assistant_telegram.Intent'),
        ),
        migrations.AlterField(
            model_name='log',
            name='intent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant_telegram.Intent'),
        ),
        migrations.AlterField(
            model_name='story_action',
            name='intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assistant_telegram.Intent'),
        ),
        migrations.AlterField(
            model_name='story_msg',
            name='intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assistant_telegram.Intent'),
        ),
        migrations.AddField(
            model_name='log',
            name='chat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant_telegram.Chat_id'),
        ),
    ]
