# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_telegram', '0007_auto_20171026_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story_msg',
            old_name='anwer',
            new_name='answer',
        ),
    ]
